version: '3'

services:
  db:
    container_name: postgresql
    image: postgres
    volumes:
      - ./postgres:/data/db
    ports:
      - 7894:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tebaex
    restart: always
  redis:
    container_name: redis
    image: redis:6.2-alpine
    volumes:
      - ./redis:/data/db
    ports:
      - 6379:6379
    restart: always
